"""
Build solution.py — the single-file hackathon deliverable.

The modular `src/` tree is the development surface. This script concatenates
every `src/*.py` into one self-contained `solution.py` that judges can run
directly. Run before each submission. Do NOT edit solution.py by hand.

Strategy:
  1. Each module's source is exec'd into a freshly-created `types.ModuleType`
     whose attributes are pre-populated with its sibling-module dependencies.
     So `from . import config` lines can be stripped while `config.LLM_MODEL`
     references still resolve.
  2. The synthetic `__file__` for each module is set to a path under a
     virtual `src/` sibling of solution.py, so `config.PROJECT_ROOT`'s
     `Path(__file__).resolve().parent.parent` math comes out identical to
     the dev tree.
  3. `evidence_report.py` gets a targeted text substitution: Jinja's
     FileSystemLoader → DictLoader with the audit_card template embedded.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
TEMPLATES = ROOT / "templates"
OUT = ROOT / "solution.py"

# Topological order — leaves first, pipeline (which imports everything) near
# the end, mock_seed last (imports extract_params).
MODULE_ORDER = [
    "config",
    "ingest",
    "extract_text",
    "segment_brand",
    "llm_client",
    "step_graph",
    "extract_params",
    "validate",
    "access_score",
    "evidence_report",
    "visualize",
    "pipeline",
    "holdout",
    "mock_seed",
]

# Which sibling modules each module imports from (`from . import X`).
DEPS = {
    "config": [],
    "ingest": ["config"],
    "extract_text": ["config"],
    "segment_brand": ["config", "extract_text"],
    "llm_client": ["config"],
    "step_graph": ["config"],
    "extract_params": ["config", "llm_client"],
    "validate": ["config", "step_graph"],
    "access_score": ["config", "step_graph"],
    "evidence_report": ["config", "access_score"],
    "visualize": ["config"],
    "pipeline": [
        "config", "ingest", "extract_text", "segment_brand",
        "extract_params", "step_graph", "validate", "access_score",
        "llm_client",
    ],
    "holdout": ["config", "ingest", "pipeline"],
    "mock_seed": [
        "config", "extract_params", "extract_text", "ingest",
        "llm_client", "segment_brand",
    ],
}


def strip_relative_imports(src: str) -> str:
    """Remove `from . import …` lines. Deps are injected into the module
    namespace before exec, so these imports become unnecessary."""
    out_lines: list[str] = []
    in_paren_block = False
    for line in src.splitlines():
        if in_paren_block:
            if ")" in line:
                in_paren_block = False
            continue
        stripped = line.lstrip()
        if re.match(r"from\s+\.\s+import\s+\(", stripped):
            if ")" not in stripped:
                in_paren_block = True
            continue
        if re.match(r"from\s+\.\s+import\s+\S", stripped):
            continue
        if re.match(r"from\s+\.\w+\s+import\s+", stripped):
            continue
        out_lines.append(line)
    return "\n".join(out_lines)


def patch_evidence_report(src: str) -> str:
    """Re-route Jinja from FileSystemLoader → DictLoader so the embedded
    template constant is used instead of templates/audit_card.html."""
    src = src.replace(
        "from jinja2 import Environment, FileSystemLoader, select_autoescape",
        "from jinja2 import Environment, DictLoader, select_autoescape",
    )
    src = src.replace(
        "loader=FileSystemLoader(str(config.TEMPLATES_DIR))",
        'loader=DictLoader({"audit_card.html": _AUDIT_CARD_TEMPLATE})',
    )
    return src


HEADER = '''"""
Arein Payer Policy Intelligence — single-file build.

GENERATED by build_single_file.py from the src/ modular tree. DO NOT EDIT
this file directly; re-run the build script after any change in src/.

Layout (mirrors arein_hackathon/):
  - solution.py (this file)
  - data/ (text, segments, llm_cache, evidence — created on demand)
  - output/ (result.csv, audit/, heatmap.png)
  - holdout/holdout_labels.csv

Run:
  python solution.py
  # or:
  python -c "import solution; solution.run_all()"

Public surface:
  run_all(...)            full pipeline → output/result.csv
  process_row(row, ...)   single-row debug
  seed_cache()            populate data/llm_cache/ with synthetic seeds
"""
from __future__ import annotations

import sys as _sys
import types as _types
from pathlib import Path as _Path

_HERE = _Path(__file__).resolve().parent
# Virtual src/ path so each module's `Path(__file__).resolve().parent.parent`
# resolves to _HERE — matches the dev tree's path layout.
_VIRTUAL_SRC = _HERE / "src"

# Embedded Jinja template (originally templates/audit_card.html). The build
# script enforces that the template contains no `\'\'\'` triple-quote sequences.
_AUDIT_CARD_TEMPLATE = r\'\'\'__AUDIT_CARD_TEMPLATE__\'\'\'

# Module registry. Each `from . import X` line in src/* was stripped by the
# build; the X attribute is injected here directly so references like
# `config.LLM_MODEL` still resolve inside the exec\'d module body.
_pkg = _types.ModuleType("solution_pkg")
_sys.modules["solution_pkg"] = _pkg


def _make_module(name, deps):
    mod = _types.ModuleType(f"solution_pkg.{name}")
    mod.__file__ = str(_VIRTUAL_SRC / f"{name}.py")
    for dep_name, dep_obj in deps.items():
        setattr(mod, dep_name, dep_obj)
    _sys.modules[f"solution_pkg.{name}"] = mod
    setattr(_pkg, name, mod)
    return mod


def _load(name, src, deps):
    mod = _make_module(name, deps)
    exec(compile(src, f"<{name}>", "exec"), mod.__dict__)
    return mod

'''

FOOTER = '''

# ════════════════════ public top-level API ════════════════════
run_all = pipeline.run_all
process_row = pipeline.process_row
seed_cache = mock_seed.seed_all


def main():
    """Driver entry point — `python solution.py`.

    Runs the full 79-row pipeline, renders audit cards + visualisations,
    and prints the location of result.csv. Honors GROQ_API_KEY from .env
    (loaded automatically by config.py) or the process environment.

    CLI:
      python solution.py            # full 79-row run
      python solution.py --limit 5  # process first 5 rows only (debug)
    """
    import argparse
    parser = argparse.ArgumentParser(
        prog="solution.py",
        description="Arein Payer Policy Intelligence — single-file submission driver.",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Process only the first N rows (debug; default: all 79).",
    )
    parser.add_argument(
        "--no-cards", action="store_true",
        help="Skip rendering audit cards + visualisations after the pipeline run.",
    )
    args = parser.parse_args()

    # Sanity-check the API key BEFORE we start the run so the evaluator
    # gets a clear error early rather than per-row failures deep in the run.
    if not config.get_api_key():
        import sys
        print(
            f"\\nERROR: {config.LLM_API_KEY_ENV} not set.\\n"
            "  Either set it in your shell or create a `.env` file at the project root\\n"
            "  with: GROQ_API_KEY=gsk_xxxxx\\n",
            file=sys.stderr,
        )
        sys.exit(2)

    print(f"Arein PA Pipeline — model={config.LLM_MODEL_FAST} (combined) + {config.LLM_MODEL} (step graph)")
    print(f"PDFs:      {config.PDF_DIR}")
    print(f"Rules:     {config.RULES_XLSX}")
    print(f"Output:    {config.RESULT_CSV}")
    print()

    df = run_all(limit=args.limit, verbose=True)

    if not args.no_cards:
        try:
            print("\\nRendering audit cards...")
            evidence_report.render_all()
            evidence_report.render_index()
            print(f"Audit cards: {config.AUDIT_DIR}")
            print("\\nRendering visualisations...")
            visualize.render_heatmap()
            visualize.render_score_distribution()
            print(f"Heatmap:     {config.HEATMAP_PNG}")
        except Exception as exc:  # noqa: BLE001
            print(f"  (audit/visualisation step skipped: {exc})")

    print(f"\\nDone. {len(df)} rows written to {config.RESULT_CSV}")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    template = (TEMPLATES / "audit_card.html").read_text(encoding="utf-8")
    if "'''" in template:
        raise RuntimeError(
            "audit_card.html contains triple-single-quotes — build script "
            "uses ''' as the embedding fence; switch to base64 encoding."
        )

    header = HEADER.replace("__AUDIT_CARD_TEMPLATE__", template)

    parts: list[str] = [header]
    for mod_name in MODULE_ORDER:
        src_path = SRC / f"{mod_name}.py"
        if not src_path.exists():
            print(f"  WARN: {src_path} not found, skipping")
            continue
        src = src_path.read_text(encoding="utf-8")
        src = strip_relative_imports(src)
        if mod_name == "evidence_report":
            src = patch_evidence_report(src)
        if "'''" in src:
            raise RuntimeError(
                f"{mod_name}.py contains triple-single-quotes — switch this "
                "module to a different embedding scheme."
            )
        # Raw triple-quoted string can't end with an unbalanced backslash; the
        # tokenizer treats the final backslash as escaping the closing quote.
        if src.endswith("\\"):
            raise RuntimeError(
                f"{mod_name}.py ends with a backslash — incompatible with "
                "raw triple-quoted embedding."
            )

        deps_list = DEPS.get(mod_name, [])
        dep_entries = [f'"{d}": _pkg.{d}' for d in deps_list]
        # evidence_report needs the embedded template injected as a module
        # global because its module-level Jinja init reads it eagerly.
        if mod_name == "evidence_report":
            dep_entries.append('"_AUDIT_CARD_TEMPLATE": _AUDIT_CARD_TEMPLATE')
        deps_dict = "{" + ", ".join(dep_entries) + "}"

        parts.append(f"\n\n# ════════════════════ MODULE: {mod_name} ════════════════════\n")
        # `r'''...'''` preserves backslash literals in the embedded source
        # (e.g., regex patterns, `.replace("\\", "_")`). The triple-quote
        # invariant is enforced above.
        parts.append(f"_src_{mod_name} = r'''")
        parts.append(src)
        parts.append("'''\n")
        parts.append(f"{mod_name} = _load('{mod_name}', _src_{mod_name}, {deps_dict})\n")

    parts.append(FOOTER)
    out_text = "".join(parts)

    OUT.write_text(out_text, encoding="utf-8")
    line_count = out_text.count("\n")
    print(f"Wrote {OUT} ({len(out_text):,} chars, {line_count:,} lines)")


if __name__ == "__main__":
    main()
