"""
Bundle the submission into a single ZIP for upload.

The hackathon's CODE deliverable is one file (`solution.py`, generated by
`build_single_file.py` from the modular `src/` tree). We rebuild it
automatically before zipping so the bundled artifact is always fresh.

Includes:
  - solution.py (the single-file code deliverable — required)
  - result.csv (the structured output deliverable)
  - notebook.ipynb (judges' entrypoint for re-running)
  - src/ (modular dev tree — kept as a readable reference alongside solution.py)
  - tests/ (unit tests + offline smoke tests)
  - templates/ (Jinja audit-card template — source of truth for the
    embedded string in solution.py)
  - data/llm_cache/ (so judges can re-run without a live API key)
  - output/ (result.csv, heatmap, audit cards, score distribution)
  - holdout/ (hand-labelled rows + holdout report)
  - README.md, requirements.txt, build_single_file.py

Excludes: data/text/, data/segments/, data/evidence/ (re-generated on run).
"""
from __future__ import annotations

import subprocess
import sys
import zipfile
from pathlib import Path

from src import config


def _rebuild_solution_py() -> Path:
    """Re-run build_single_file.py so the bundled solution.py reflects the
    current src/ state. Fail loudly if the build script errors — we don't
    want to ship a stale or broken single-file."""
    root = config.PROJECT_ROOT
    build_script = root / "build_single_file.py"
    if not build_script.exists():
        raise FileNotFoundError(
            f"{build_script} missing — solution.py cannot be regenerated."
        )
    result = subprocess.run(
        [sys.executable, str(build_script)],
        cwd=str(root), capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"build_single_file.py failed (exit {result.returncode}):\n"
            f"{result.stderr or result.stdout}"
        )
    solution = root / "solution.py"
    if not solution.exists():
        raise RuntimeError("build_single_file.py succeeded but solution.py is missing")
    return solution


def build_zip(zip_path: Path | None = None) -> Path:
    zip_path = zip_path or (config.PROJECT_ROOT / "arein_submission.zip")
    root = config.PROJECT_ROOT

    # Always regenerate solution.py from the current src/ state. Doing this
    # here (rather than relying on the user to remember) means the bundled
    # single-file artifact and the modular tree can never drift.
    _rebuild_solution_py()

    include_dirs = ["src", "tests", "templates", "data/llm_cache",
                    "output", "holdout"]
    include_files = ["solution.py", "build_single_file.py",
                     "notebook.ipynb", "README.md", "requirements.txt",
                     "package_submission.py"]

    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for d in include_dirs:
            for p in (root / d).rglob("*"):
                if p.is_file() and "__pycache__" not in p.parts:
                    z.write(p, p.relative_to(root))
        for f in include_files:
            fp = root / f
            if fp.exists():
                z.write(fp, fp.relative_to(root))
    return zip_path


if __name__ == "__main__":
    out = build_zip()
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB)")
